#!/usr/bin/env bash

# Ask for the administrator password upfront
sudo -v

# Install Homebrew
if test ! $(which brew)
then
  echo " → Installing Homebrew for package management..."
  ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
fi
brew update
brew upgrade

echo "→ Installing packages using Homebrew..."
brew install $(cat brew/brewfile|grep -v "#")

echo "→ Installing Fisherman, a plugin manager for Fish..."
curl -Lo ~/.config/fish/functions/fisher.fish --create-dirs git.io/fisherman

echo "→ Configuring Git..."
# Personal information in your .gitlocal, not .gitconfig!
ln -s ~/dotfiles/git/config ~/.gitconfig
ln -s ~/dotfiles/git/attributes ~/.gitattributes
ln -s ~/dotfiles/git/ignore_global ~/.gitignore_global

# Set Fish as default shell
echo "→ Configuring Fish..."
echo '/usr/local/bin/fish' | sudo tee -a /etc/shells > /dev/null
chsh -s /usr/local/bin/fish
# Set custom settings
ln -s ~/dotfiles/fish/config.fish ~/.config/fish/config.fish
ln -s ~/dotfiles/fish/utils ~/.config/fish/functions/custom
ln -s ~/dotfiles/fish/fishfile ~/.config/fish/fishfile
# Switch to fish
fish
# Run fisher
fisher

# Install nvm, node and global npm packages
curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.2/install.sh | bash
nvm install stable
echo "→ Installing npm packages..."
npm install -g $(cat misc/npm_globals|grep -v "#")

# Set macOS defaults
echo "→ Set macOS defaults... (It'll shut down Terminal!)"
sh misc/macos
