#!/usr/bin/env bash

# Ask for the administrator password upfront
sudo -v

if test ! $(which brew)
then
  echo " → Installing Homebrew for package management..."
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
fi

echo "→ Installing applications..."
brew tap homebrew/cask-versions # allows apps' alternative versions, like Canary
brew install --cask $(cat brew/caskfile|grep -v "#")

echo "→ Installing fonts..."
homebrew/cask-fonts
brew install --cask $(cat brew/fontfile|grep -v "#")
