#!/usr/bin/env bash

# Ask for the administrator password upfront
sudo -v


# --------------–-------–--------–--------–-------–--–-----
# System packages
# --------------–-------–--------–--------–-------–--–-----
# Install Ruby Version Manager (rvm.io)
curl -sSL https://get.rvm.io | bash -s stable
source "$HOME"/.rvm/scripts/rvm | rvm install ruby-head

# Install Homebrew for package management, if not installed
if test ! $(which brew)
then
  echo " → Installing Homebrew for package management..."
  ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
fi

# Make sure Homebrew is up to date
brew update
brew upgrade

# Command-line tools and utils
# --------------–-------–--------–--------–-------–--–-----
echo "→ Installing packages using Homebrew..."

# Install all packages listed in the brewfile
brew install $(cat brewfile|grep -v "#")

# Install oh-my-zsh, a framework for Zsh 
echo "→ Installing oh-my-zsh, a framework for Zsh.."
sh -c "$(curl -fsSL https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"

# Install z, which  tracks the most used directories
curl https://raw.github.com/rupa/z/master/z.sh > ~/dotfiles/utils/z.sh

# --------------–-------–--------–--------–-------–--–-----
# General packages
# --------------–-------–--------–--------–-------–--–-----
# Node.js
echo "→ Installing npm packages.."
npm install -g $(cat npm/npmGlobals|grep -v "#")

# Ruby
echo "→ Installing gems.."
gem install $(cat ruby/gemfile|grep -v "#")

# Python (not versioned!)
# pip install $(cat python/pipfile)

# Atom
# TODO
#echo "→ Installing Atomp packages.."
#apm install --packages-file atom/atomfile


# --------------–-------–--------–--------–-------–--–-----
# Link dotfiles
# --------------–-------–--------–--------–-------–--–-----
echo "→ Linking Git dotfiles..."
# Personal information in your .gitlocal, not .gitconfig!
ln -s ~/dotfiles/git/config ~/.gitconfig
ln -s ~/dotfiles/git/attributes ~/.gitattributes
ln -s ~/dotfiles/git/ignore_global ~/.gitignore_global

echo "→ Linking Zsh dotfiles..."
# Remove that messy default zshrc file
rm ~/.zshrc
# And set the awesome ones!
ln -s ~/dotfiles/zshrc ~/.zshrc

echo "→ Linking dotfiles..."


# --------------–-------–--------–--------–-------–--–-----
# System preferences
# --------------–-------–--------–--------–-------–--–-----
# It'll shut down Terminal!
echo "→ Set OS X defaults... (It'll shut down Terminal!)"
sh osx/defaults