#!/usr/bin/env bash

# Ask for the administrator password upfront
sudo -v


# --------------–-------–--------–--------–-------–--–-----
# System packages
# --------------–-------–--------–--------–-------–--–-----
# Install Ruby Version Manager (rvm.io)
curl -sSL https://get.rvm.io | bash -s stable
source "$HOME"/.rvm/scripts/rvm | rvm install ruby-head

# Install Homebrew for package management, if not installed
if test ! $(which brew)
then
  echo " → Installing Homebrew for package management..."
  ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
fi

# Make sure Homebrew is up to date
brew update
brew upgrade

# Command-line tools and utils
# --------------–-------–--------–--------–-------–--–-----
echo "→ Installing packages using Homebrew..."

# Install all packages listed in the brewfile
brew install $(cat brew/brewfile|grep -v "#")

# Install oh-my-zsh, a framework for Zsh
echo "→ Installing oh-my-zsh, a framework for Zsh.."
sh -c "$(curl -fsSL https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"

# Install zsh-syntax-highlighting plugin
git clone git://github.com/zsh-users/zsh-syntax-highlighting.git ~/.oh-my-zsh/custom/plugins


# --------------–-------–--------–--------–-------–--–-----
# Specific packages
# --------------–-------–--------–--------–-------–--–-----
# Node.js
echo "→ Installing npm packages..."
npm install -g $(cat npm/npmGlobals|grep -v "#")


# --------------–-------–--------–--------–-------–--–-----
# Command line tweaks, linking stuff
# --------------–-------–--------–--------–-------–--–-----
echo "→ Linking Git dotfiles..."
# Personal information in your .gitlocal, not .gitconfig!
ln -s ~/dotfiles/git/config ~/.gitconfig
ln -s ~/dotfiles/git/attributes ~/.gitattributes
ln -s ~/dotfiles/git/ignore_global ~/.gitignore_global

echo "→ Linking Zsh dotfiles..."
# Set Zsh as default shell
chsh -s $(which zsh)
# Remove that messy default zshrc file
rm ~/.zshrc
# And set the awesome ones!
ln -s ~/dotfiles/zsh/zshrc ~/.zshrc
ln -s ~/dotfiles/zsh/custom ~/.oh-my-zsh

echo "→ Configure iTerm..."
rm ~/Library/Preferences/com.googlecode.iterm2.plist
ln -s ~/dotfiles/iterm/com.googlecode.iterm2.plist ~/Library/Preferences/com.googlecode.iterm2.plist


# --------------–-------–--------–--------–-------–--–-----
# System preferences
# --------------–-------–--------–--------–-------–--–-----
# It'll shut down Terminal!
echo "→ Set OS X defaults... (It'll shut down Terminal!)"
sh osx/defaults
