#!/usr/bin/env bash

# Ask for the administrator password upfront
sudo -v

# Install Homebrew for package management, if not installed
if test ! $(which brew)
then
  echo " → Installing Homebrew for package management..."
  ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
fi


# --------------–-------–--------–--------–-------–
# Applications
# --------------–-------–--------–--------–-------–
echo "→ Installing applications..."

# Set up Cask, for Homebrew
brew tap caskroom/cask

# Set up Caskroom-versions, which allows apps' alternative versions, like Canary
brew tap caskroom/versions

# Install all apps listed in the caskfile
brew cask install $(cat brew/caskfile|grep -v "#")


# --------------–-------–--------–--------–-------–
# Fonts
# --------------–-------–--------–--------–-------–
echo "→ Installing fonts..."

# Set up Caskroom-fonts, which allows to use the Homebrew-style CLI workflow for fonts
brew tap caskroom/fonts

# Install all fonts listed in the fontfile
brew cask install $(cat brew/fontfile|grep -v "#")
