#!/usr/bin/env bash

# Ask for the administrator password upfront
sudo -v

if test ! $(which brew)
then
  echo " → Installing Homebrew for package management..."
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
fi
brew update
brew upgrade

echo "→ Installing packages..."
brew install $(cat brew/brewfile|grep -v "#")

echo "→ Configuring Git..."
# Personal information in your .gitlocal, not .gitconfig!
ln -s ~/dotfiles/git/config ~/.gitconfig
ln -s ~/dotfiles/git/attributes ~/.gitattributes
ln -s ~/dotfiles/git/ignore_global ~/.gitignore_global

# Set Fish as default shell
echo "→ Configuring Fish..."
echo '/usr/local/bin/fish' | sudo tee -a /etc/shells > /dev/null
chsh -s /usr/local/bin/fish
# Set custom settings
ln -s ~/dotfiles/fish/config.fish ~/.config/fish/config.fish
ln -s ~/dotfiles/fish/utils ~/.config/fish/functions/custom
ln -s ~/dotfiles/fish/fishfile ~/.config/fish/fishfile
# Switch to fish
fish
# Run fisher
fisher

# Set macOS defaults
echo "→ Set macOS defaults... (It'll shut down Terminal!)"
sh misc/macos
